# Build, and deploy ovc.uoguelph.ca
pool:
  vmImage: ubuntu-latest
  demands: npm
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(3a1e4cf8-5973-49b0-bebf-d31a390189cf)'
    subscriptionId: '3a1e4cf8-5973-49b0-bebf-d31a390189cf'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ovc-main-web'
    location: 'Canada East'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Complete'
