# Build, and deploy ovc.uoguelph.ca

variables:
  SUBSCRIPTION_ID: '3a1e4cf8-5973-49b0-bebf-d31a390189cf'
  AZURE_SUBSCRIPTION: 'Pay-As-You-Go(3a1e4cf8-5973-49b0-bebf-d31a390189cf)'
  AZURE_RESOURCE_MANAGER_CONNECTION: 'Pay-As-You-Go(3a1e4cf8-5973-49b0-bebf-d31a390189cf)'
  RESOURCE_GROUP_NAME: 'ovcmainwebrg'
  STORAGE_ACCOUNT_NAME: 'mainovcstorage'

pool:
  vmImage: windows-latest
  demands: npm

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'az deploy'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION)
    subscriptionId: $(SUBSCRIPTION_ID)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RESOURCE_GROUP_NAME)
    location: 'Canada East'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Complete'
- task: AzureCLI@2
  displayName: 'enable static website'
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob service-properties update --account-name $(STORAGE_ACCOUNT_NAME) --static-website  --index-document index.html'
- task: AzureFileCopy@3
  displayName: 'copy files'
  inputs:
    SourcePath: 'public'
    azureSubscription: $(AZURE_SUBSCRIPTION)
    Destination: 'AzureBlob'
    storage: $(STORAGE_ACCOUNT_NAME)
    ContainerName: '$web'
